export const AUTH_FETCH_USER_VERIFICATION_PENDING  = 'AUTH_FETCH_USER_VERIFICATION_PENDING'
export const AUTH_FETCH_USER_VERIFICATION_FINISHED = 'AUTH_FETCH_USER_VERIFICATION_FINISHED'
export const AUTH_FETCH_USER_VERIFICATION_ERROR    = 'AUTH_FETCH_USER_VERIFICATION_ERROR'

export const AUTH_FETCH_TOKEN_VALIDATION_PENDING  = 'AUTH_FETCH_TOKEN_VALIDATION_PENDING'
export const AUTH_FETCH_TOKEN_VALIDATION_FINISHED = 'AUTH_FETCH_TOKEN_VALIDATION_FINISHED'
export const AUTH_FETCH_TOKEN_VALIDATION_ERROR    = 'AUTH_FETCH_TOKEN_VALIDATION_ERROR'
